# Generated by Django 4.2.1 on 2023-05-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_korisnik_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnik',
            name='role',
            field=models.CharField(choices=[('prof', 'profesor'), ('stu', 'student'), ('admin', 'admin')], default='stu', max_length=50),
        ),
        migrations.AlterField(
            model_name='korisnik',
            name='status',
            field=models.CharField(choices=[('none', 'None'), ('izv', 'izvanredni student'), ('red', 'redovni student')], default='none', max_length=50),
        ),
    ]
