# Generated by Django 4.2.1 on 2023-05-25 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_predmeti_izborni'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpisniList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('none', 'none'), ('up', 'upisan'), ('po', 'polozen')], default='none', max_length=64)),
                ('predmet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.predmeti')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
