# Generated by Django 4.2.1 on 2023-05-25 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_upisnilist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upisnilist',
            old_name='predmet_id',
            new_name='predmet',
        ),
        migrations.RenameField(
            model_name='upisnilist',
            old_name='student_id',
            new_name='student',
        ),
    ]
