# Generated by Django 4.2.1 on 2023-05-25 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_predmet_id_upisnilist_predmet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('none', 'none'), ('as', 'assigned')], default='none', max_length=64)),
                ('predmet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.predmeti')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
