# Generated by Django 4.2.1 on 2023-05-25 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_assignedcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedcourse',
            name='profesor',
            field=models.ForeignKey(limit_choices_to={'role': 'prof'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='upisnilist',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'stu'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='assignedcourse',
            unique_together={('profesor', 'predmet')},
        ),
        migrations.AlterUniqueTogether(
            name='upisnilist',
            unique_together={('student', 'predmet')},
        ),
        migrations.RemoveField(
            model_name='assignedcourse',
            name='status',
        ),
    ]
