# Generated by Django 4.2.1 on 2023-05-25 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_assignedcourse_profesor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedcourse',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
