# Generated by Django 4.2.1 on 2023-05-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_assignedcourse_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upisnilist',
            name='status',
            field=models.CharField(choices=[('up', 'upisan'), ('po', 'polozen'), ('ip', 'izgubio potpis')], max_length=64),
        ),
    ]
